name: app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=21.2.4
  - pip:
    - azureml-defaults==1.39.0
    - azureml-mlflow==1.39.0
    - azureml-contrib-dataset==1.39.0
    - tensorflow-cpu==2.8.0
    - mlflow==1.24.0